name: 'GreatUtils'
version: '${project.version}'
main: io.github.greatericontop.greatutils.GreatUtils
api-version: '1.19'
authors: [greateric]

commands:
  execlater:
    description: Execute a command later.
    usage: '§cUsage: /execlater <delay> <command...>'
    permission: greatutils.execlater
  execlaterrng:
    description: Execute a command after, with random delay.
    usage: '§cUsage: /execlaterrng <min delay> <max delay> <command...>'
    permission: greatutils.execlater
  exectimer:
    description: Execute a command repeatedly on a timer.
    usage: '§cUsage: /exectimer [<number of times> <interval>  or  <interval> <number of times>] <command...>'
    permission: greatutils.exectimer
  mytasks:
    description: View your scheduled tasks.
    usage: '/mytasks'
    permission: greatutils.mytasks
  canceltask:
    description: Cancel a scheduled task.
    usage: '§cUsage: /canceltask <task ID> [<another task ID>]  or  /canceltask all'
    permission: greatutils.canceltask
  sudo:
    description: Execute a command as another player.
    usage: '§cUsage: /sudo <player> <chat or command...>'
    permission: greatutils.sudo
  kit:
    description: Manage kits
    usage: '§cUsage: /kit <kit> | /kit <kit> update | /kit <kit>'
    permission: greatutils.kit

permissions:
  greatutils.execlater:
    default: op
  greatutils.exectimer:
    default: op
  greatutils.mytasks:
    default: true
  greatutils.canceltask:
    default: op
  greatutils.sudo:
    default: op
  greatutils.kit:
    default: op
