name: 'GreatUtils'
version: '${project.version}'
main: io.github.greatericontop.greatutils.GreatUtils
api-version: '1.19'
authors: [greateric]

commands:
  execlater:
    description: Execute a command later.
    usage: '§cUsage: /execlater <delay> <command...>'
    permission: greatutils.execlater
  mytasks:
    description: View your scheduled tasks.
    usage: '/mytasks'
    permission: greatutils.mytasks

permissions:
  greatutils.execlater:
    default: op
  greatutils.mytasks:
    default: true
