name: 'GreatUtils'
version: '${project.version}'
main: io.github.greatericontop.greatutils.GreatUtils
api-version: '1.19'
authors: [greateric]

commands:
  execlater:
    description: Execute a command later.
    usage: /execlater <delay> <command...>
    permission: greatutils.execlater

permissions:
  greatutils.execlater:
    default: op
